import Sprockell
prog0 =
	[Jump (Abs (1))
	, Load (ImmValue (50)) (4)
	, Compute Add (5) (4) (5)
	, Load (ImmValue (0)) (2)
	, Load (ImmValue (0)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (3)) (2)
	, Load (ImmValue (0)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (0)) (2)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (2)) (2)
	, Load (ImmValue (1)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (1)) (2)
	, WriteInstr (2) (DirAddr (81))
	, Load (ImmValue (1)) (2)
	, WriteInstr (2) (DirAddr (82))
	, ReadInstr (DirAddr (91))
	, Receive (2)
	, Load (ImmValue (1)) (3)
	, Compute Xor (2) (3) (2)
	, Branch (2) (Abs (29))
	, ReadInstr (DirAddr (92))
	, Receive (2)
	, Load (ImmValue (1)) (3)
	, Compute Xor (2) (3) (2)
	, Branch (2) (Abs (34))
	, Load (ImmValue (0)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (32)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (32)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, WriteInstr (2) (DirAddr (65536))
	, EndProg
	]
prog1 =
	[Jump (Abs (1))
	, Load (ImmValue (50)) (4)
	, Compute Add (5) (4) (5)
	, ReadInstr (DirAddr (81))
	, Receive (2)
	, Load (ImmValue (1)) (3)
	, Compute Xor (2) (3) (2)
	, Branch (2) (Abs (3))
	, Load (ImmValue (1)) (2)
	, Load (ImmValue (2)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (2)) (2)
	, Load (ImmValue (2)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (0)) (2)
	, Load (ImmValue (3)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (1)) (2)
	, Load (ImmValue (3)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (3)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (4)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (1)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (5)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (0)) (2)
	, Load (ImmValue (6)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (1)) (3)
	, Load (ImmValue (5)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Load (ImmValue (6)) (4)
	, Compute Add (4) (5) (4)
	, Load (IndAddr (4)) (4)
	, Compute Equal (2) (4) (2)
	, Compute And (2) (3) (3)
	, Load (ImmValue (7)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (4)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Load (ImmValue (7)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, Compute And (2) (3) (2)
	, Load (ImmValue (8)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (8)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Branch (2) (Rel (2))
	, Jump (Abs (78))
	, Jump (Abs (30))
	, Load (ImmValue (0)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (9)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (200)) (2)
	, Load (ImmValue (10)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (9)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Load (ImmValue (10)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, Compute Lt (2) (3) (2)
	, Load (ImmValue (11)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (11)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Branch (2) (Rel (2))
	, Jump (Abs (147))
	, Load (ImmValue (0)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (12)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (1)) (2)
	, Load (ImmValue (13)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (12)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Load (ImmValue (13)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, Compute Add (2) (3) (2)
	, Load (ImmValue (14)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (0)) (2)
	, Load (ImmValue (14)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (0)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (15)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (15)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, WriteInstr (2) (DirAddr (65536))
	, Jump (Abs (78))
	, Load (ImmValue (0)) (2)
	, Load (ImmValue (16)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (2)) (2)
	, Load (ImmValue (16)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (1)) (2)
	, WriteInstr (2) (DirAddr (91))
	, EndProg
	]
prog2 =
	[Jump (Abs (1))
	, Load (ImmValue (50)) (4)
	, Compute Add (5) (4) (5)
	, ReadInstr (DirAddr (82))
	, Receive (2)
	, Load (ImmValue (1)) (3)
	, Compute Xor (2) (3) (2)
	, Branch (2) (Abs (3))
	, Load (ImmValue (1)) (2)
	, Load (ImmValue (17)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (3)) (2)
	, Load (ImmValue (17)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (1)) (2)
	, Load (ImmValue (18)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (1)) (2)
	, Load (ImmValue (18)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (2)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (19)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (1)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (20)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (1)) (2)
	, Load (ImmValue (21)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (1)) (3)
	, Load (ImmValue (20)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Load (ImmValue (21)) (4)
	, Compute Add (4) (5) (4)
	, Load (IndAddr (4)) (4)
	, Compute Equal (2) (4) (2)
	, Compute And (2) (3) (3)
	, Load (ImmValue (22)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (19)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Load (ImmValue (22)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, Compute And (2) (3) (2)
	, Load (ImmValue (23)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (23)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Branch (2) (Rel (2))
	, Jump (Abs (78))
	, Jump (Abs (30))
	, Load (ImmValue (0)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (24)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (300)) (2)
	, Load (ImmValue (25)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (24)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Load (ImmValue (25)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, Compute Lt (2) (3) (2)
	, Load (ImmValue (26)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (26)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Branch (2) (Rel (2))
	, Jump (Abs (147))
	, Load (ImmValue (0)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (27)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (1)) (2)
	, Load (ImmValue (28)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (27)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, Load (ImmValue (28)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, Compute Add (2) (3) (2)
	, Load (ImmValue (29)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (0)) (2)
	, Load (ImmValue (29)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (0)) (2)
	, ReadInstr (IndAddr (2))
	, Receive (3)
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (30)) (4)
	, Compute Add (4) (5) (4)
	, Store (3) (IndAddr (4))
	, Load (ImmValue (30)) (2)
	, Compute Add (2) (5) (2)
	, Load (IndAddr (2)) (2)
	, WriteInstr (2) (DirAddr (65536))
	, Jump (Abs (78))
	, Load (ImmValue (0)) (2)
	, Load (ImmValue (31)) (4)
	, Compute Add (4) (5) (4)
	, Store (2) (IndAddr (4))
	, Load (ImmValue (3)) (2)
	, Load (ImmValue (31)) (3)
	, Compute Add (3) (5) (3)
	, Load (IndAddr (3)) (3)
	, WriteInstr (3) (IndAddr (2))
	, Load (ImmValue (1)) (4)
	, Compute Add (4) (2) (2)
	, Load (ImmValue (1)) (2)
	, WriteInstr (2) (DirAddr (92))
	, EndProg
	]
main = run [prog0, prog1, prog2]
